eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus