server:
  port: 4002

spring:
  application:
    name: SERVICE2

management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost