server:
  port: 7000
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Onedrive/Desktop/sample-config-repo
          clone-on-start: true
  application:
    name: CONFIG-SERVER

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost